# Generated by Django 5.2.12 on 2026-03-31 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('NFL', 'NFL Football'), ('NBA', 'NBA Basketball'), ('NHL', 'NHL Hockey'), ('MLB', 'MLB Baseball'), ('SOCCER', 'Soccer')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contract_type', models.CharField(choices=[('HOME_WIN', 'Home Win'), ('AWAY_WIN', 'Away Win'), ('DRAW', 'Draw'), ('OVER', 'Over'), ('UNDER', 'Under'), ('PLAYER_PROP', 'Player Prop'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('coinbase_product_id', models.CharField(max_length=100, unique=True)),
                ('coinbase_contract_id', models.CharField(blank=True, max_length=100)),
                ('line', models.FloatField(blank=True, null=True)),
                ('game_date', models.DateField(blank=True, null=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='sports.game')),
            ],
            options={
                'ordering': ['-game_date', 'sport'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_price', models.FloatField()),
                ('no_price', models.FloatField()),
                ('mid_price', models.FloatField()),
                ('volume_24h', models.FloatField(blank=True, null=True)),
                ('open_interest', models.FloatField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='markets.marketcontract')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'get_latest_by': 'fetched_at',
            },
        ),
        migrations.CreateModel(
            name='EdgeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('NFL', 'NFL Football'), ('NBA', 'NBA Basketball'), ('NHL', 'NHL Hockey'), ('MLB', 'MLB Baseball'), ('SOCCER', 'Soccer')], max_length=10)),
                ('model_probability', models.FloatField()),
                ('market_probability', models.FloatField()),
                ('edge', models.FloatField()),
                ('kelly_fraction', models.FloatField()),
                ('confidence', models.FloatField(default=0.5)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('EXPIRED', 'Expired'), ('HIT', 'Resolved – Model Correct'), ('MISS', 'Resolved – Model Wrong')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_alerts', to='markets.marketcontract')),
                ('market_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='markets.marketprice')),
            ],
            options={
                'ordering': ['-edge', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marketcontract',
            index=models.Index(fields=['sport', 'is_active'], name='markets_mar_sport_99fcd7_idx'),
        ),
        migrations.AddIndex(
            model_name='marketcontract',
            index=models.Index(fields=['game_date'], name='markets_mar_game_da_d9ab9a_idx'),
        ),
        migrations.AddIndex(
            model_name='marketcontract',
            index=models.Index(fields=['is_active', 'is_resolved'], name='markets_mar_is_acti_756dda_idx'),
        ),
        migrations.AddIndex(
            model_name='marketprice',
            index=models.Index(fields=['contract', 'fetched_at'], name='markets_mar_contrac_296c79_idx'),
        ),
        migrations.AddIndex(
            model_name='edgealert',
            index=models.Index(fields=['sport', 'status'], name='markets_edg_sport_98262c_idx'),
        ),
        migrations.AddIndex(
            model_name='edgealert',
            index=models.Index(fields=['status', 'created_at'], name='markets_edg_status_62e7c0_idx'),
        ),
    ]
