# Generated by Django 5.2.12 on 2026-03-31 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_bankroll', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('kelly_fraction', models.FloatField(default=0.25, help_text='Fraction of Kelly to use (0.25 = quarter-Kelly)')),
                ('max_bet_pct', models.FloatField(default=0.05, help_text='Max % of bankroll per bet')),
                ('edge_threshold', models.FloatField(default=0.05, help_text='Minimum edge to flag as alert')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bankroll_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankrollSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('starting_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ending_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_wagered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active_bets', models.IntegerField(default=0)),
                ('sport_pnl', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankroll_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('NFL', 'NFL Football'), ('NBA', 'NBA Basketball'), ('NHL', 'NHL Hockey'), ('MLB', 'MLB Baseball'), ('SOCCER', 'Soccer')], max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('is_yes', models.BooleanField(default=True)),
                ('amount_wagered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('shares', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('predicted_edge', models.FloatField(blank=True, null=True)),
                ('kelly_fraction_used', models.FloatField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('PUSH', 'Push'), ('VOID', 'Void')], default='PENDING', max_length=10)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bet_records', to='markets.marketcontract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_at'],
                'indexes': [models.Index(fields=['user', 'outcome'], name='bankroll_be_user_id_e1af79_idx'), models.Index(fields=['user', 'sport'], name='bankroll_be_user_id_f16de4_idx'), models.Index(fields=['placed_at'], name='bankroll_be_placed__077d99_idx')],
            },
        ),
    ]
