# Generated by Django 5.2.12 on 2026-03-31 04:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('NFL', 'NFL Football'), ('NBA', 'NBA Basketball'), ('NHL', 'NHL Hockey'), ('MLB', 'MLB Baseball'), ('SOCCER', 'Soccer')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['sport', 'name'],
                'unique_together': {('sport', 'abbreviation')},
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('NFL', 'NFL Football'), ('NBA', 'NBA Basketball'), ('NHL', 'NHL Hockey'), ('MLB', 'MLB Baseball'), ('SOCCER', 'Soccer')], max_length=10)),
                ('year', models.IntegerField()),
                ('label', models.CharField(max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='sports.league')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('sport', 'league', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('NFL', 'NFL Football'), ('NBA', 'NBA Basketball'), ('NHL', 'NHL Hockey'), ('MLB', 'MLB Baseball'), ('SOCCER', 'Soccer')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('conference', models.CharField(blank=True, max_length=50)),
                ('division', models.CharField(blank=True, max_length=50)),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('venue_city', models.CharField(blank=True, max_length=100)),
                ('venue_timezone', models.CharField(default='America/New_York', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('espn_id', models.CharField(blank=True, max_length=20)),
                ('nfl_data_id', models.CharField(blank=True, max_length=20)),
                ('nba_api_id', models.IntegerField(blank=True, null=True)),
                ('nhl_api_id', models.IntegerField(blank=True, null=True)),
                ('mlb_api_id', models.IntegerField(blank=True, null=True)),
                ('football_data_id', models.IntegerField(blank=True, null=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='sports.league')),
            ],
            options={
                'ordering': ['sport', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('NFL', 'NFL Football'), ('NBA', 'NBA Basketball'), ('NHL', 'NHL Hockey'), ('MLB', 'MLB Baseball'), ('SOCCER', 'Soccer')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('jersey_number', models.CharField(blank=True, max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('espn_id', models.CharField(blank=True, max_length=20)),
                ('nfl_gsis_id', models.CharField(blank=True, max_length=20)),
                ('nba_api_id', models.IntegerField(blank=True, null=True)),
                ('nhl_api_id', models.IntegerField(blank=True, null=True)),
                ('mlb_api_id', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='sports.team')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('NFL', 'NFL Football'), ('NBA', 'NBA Basketball'), ('NHL', 'NHL Hockey'), ('MLB', 'MLB Baseball'), ('SOCCER', 'Soccer')], max_length=10)),
                ('game_date', models.DateField()),
                ('game_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('FINAL', 'Final'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('home_period_scores', models.JSONField(blank=True, default=dict)),
                ('away_period_scores', models.JSONField(blank=True, default=dict)),
                ('overtime_periods', models.IntegerField(default=0)),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('neutral_site', models.BooleanField(default=False)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('home_rest_days', models.IntegerField(blank=True, null=True)),
                ('away_rest_days', models.IntegerField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=50)),
                ('espn_id', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='sports.season')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='sports.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='sports.team')),
            ],
            options={
                'ordering': ['-game_date', 'game_time'],
            },
        ),
        migrations.CreateModel(
            name='TeamSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('points_per_game', models.FloatField(blank=True, null=True)),
                ('points_allowed_per_game', models.FloatField(blank=True, null=True)),
                ('pace', models.FloatField(blank=True, null=True)),
                ('offensive_rating', models.FloatField(blank=True, null=True)),
                ('defensive_rating', models.FloatField(blank=True, null=True)),
                ('home_wins', models.IntegerField(default=0)),
                ('home_losses', models.IntegerField(default=0)),
                ('away_wins', models.IntegerField(default=0)),
                ('away_losses', models.IntegerField(default=0)),
                ('extra_stats', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='sports.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='sports.team')),
            ],
            options={
                'ordering': ['-season__year'],
            },
        ),
        migrations.CreateModel(
            name='InjuryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OUT', 'Out'), ('DOUBTFUL', 'Doubtful'), ('QUESTIONABLE', 'Questionable'), ('PROBABLE', 'Probable'), ('ACTIVE', 'Active'), ('IR', 'Injured Reserve')], max_length=20)),
                ('body_part', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injuries', to='sports.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='sports.player')),
            ],
            options={
                'ordering': ['-report_date', 'player__last_name'],
                'indexes': [models.Index(fields=['player', 'report_date'], name='sports_inju_player__2cb5f5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['sport'], name='sports_team_sport_011f47_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['sport', 'is_active'], name='sports_team_sport_780277_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('sport', 'abbreviation')},
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['sport', 'is_active'], name='sports_play_sport_020c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team'], name='sports_play_team_id_533f08_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['sport', 'game_date'], name='sports_game_sport_28ec42_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['sport', 'status'], name='sports_game_sport_6b6b66_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['game_date'], name='sports_game_game_da_7cf795_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('sport', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='teamseasonstats',
            unique_together={('team', 'season')},
        ),
    ]
