# Generated by Django 5.2.12 on 2026-04-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sport',
            field=models.CharField(choices=[('NFL', 'NFL Football'), ('NBA', 'NBA Basketball'), ('NHL', 'NHL Hockey'), ('MLB', 'MLB Baseball'), ('SOCCER', 'Soccer'), ('NCAAM', "NCAA Men's Basketball"), ('NCAAF', 'NCAA Football'), ('MMA', 'MMA / UFC'), ('WNBA', 'WNBA Basketball'), ('TENNIS', 'Tennis'), ('GOLF', 'PGA Golf'), ('NASCAR', 'NASCAR'), ('F1', 'Formula 1'), ('CRICKET', 'Cricket')], max_length=10),
        ),
        migrations.AlterField(
            model_name='league',
            name='sport',
            field=models.CharField(choices=[('NFL', 'NFL Football'), ('NBA', 'NBA Basketball'), ('NHL', 'NHL Hockey'), ('MLB', 'MLB Baseball'), ('SOCCER', 'Soccer'), ('NCAAM', "NCAA Men's Basketball"), ('NCAAF', 'NCAA Football'), ('MMA', 'MMA / UFC'), ('WNBA', 'WNBA Basketball'), ('TENNIS', 'Tennis'), ('GOLF', 'PGA Golf'), ('NASCAR', 'NASCAR'), ('F1', 'Formula 1'), ('CRICKET', 'Cricket')], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='sport',
            field=models.CharField(choices=[('NFL', 'NFL Football'), ('NBA', 'NBA Basketball'), ('NHL', 'NHL Hockey'), ('MLB', 'MLB Baseball'), ('SOCCER', 'Soccer'), ('NCAAM', "NCAA Men's Basketball"), ('NCAAF', 'NCAA Football'), ('MMA', 'MMA / UFC'), ('WNBA', 'WNBA Basketball'), ('TENNIS', 'Tennis'), ('GOLF', 'PGA Golf'), ('NASCAR', 'NASCAR'), ('F1', 'Formula 1'), ('CRICKET', 'Cricket')], max_length=10),
        ),
        migrations.AlterField(
            model_name='season',
            name='sport',
            field=models.CharField(choices=[('NFL', 'NFL Football'), ('NBA', 'NBA Basketball'), ('NHL', 'NHL Hockey'), ('MLB', 'MLB Baseball'), ('SOCCER', 'Soccer'), ('NCAAM', "NCAA Men's Basketball"), ('NCAAF', 'NCAA Football'), ('MMA', 'MMA / UFC'), ('WNBA', 'WNBA Basketball'), ('TENNIS', 'Tennis'), ('GOLF', 'PGA Golf'), ('NASCAR', 'NASCAR'), ('F1', 'Formula 1'), ('CRICKET', 'Cricket')], max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.CharField(choices=[('NFL', 'NFL Football'), ('NBA', 'NBA Basketball'), ('NHL', 'NHL Hockey'), ('MLB', 'MLB Baseball'), ('SOCCER', 'Soccer'), ('NCAAM', "NCAA Men's Basketball"), ('NCAAF', 'NCAA Football'), ('MMA', 'MMA / UFC'), ('WNBA', 'WNBA Basketball'), ('TENNIS', 'Tennis'), ('GOLF', 'PGA Golf'), ('NASCAR', 'NASCAR'), ('F1', 'Formula 1'), ('CRICKET', 'Cricket')], max_length=10),
        ),
    ]
