# Generated by Django 5.2.12 on 2026-04-04 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_update_sport_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injuryreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
