# Generated by Django 5.2.12 on 2026-03-31 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('NFL', 'NFL Football'), ('NBA', 'NBA Basketball'), ('NHL', 'NHL Hockey'), ('MLB', 'MLB Baseball'), ('SOCCER', 'Soccer')], max_length=10)),
                ('model_version', models.CharField(max_length=20)),
                ('total_games', models.IntegerField(default=0)),
                ('correct_predictions', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('brier_score', models.FloatField(blank=True, null=True)),
                ('log_loss', models.FloatField(blank=True, null=True)),
                ('roi', models.FloatField(blank=True, null=True)),
                ('avg_edge', models.FloatField(blank=True, null=True)),
                ('total_total_games', models.IntegerField(default=0)),
                ('correct_totals', models.IntegerField(default=0)),
                ('totals_accuracy', models.FloatField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.season')),
            ],
            options={
                'ordering': ['-computed_at'],
                'unique_together': {('sport', 'model_version', 'season')},
            },
        ),
        migrations.CreateModel(
            name='EloRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.FloatField(default=1500.0)),
                ('games_played', models.IntegerField(default=0)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elo_snapshot', to='sports.game')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elo_ratings', to='sports.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_ratings', to='sports.team')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['team', 'date'], name='analytics_e_team_id_43e4e5_idx'), models.Index(fields=['team', 'season'], name='analytics_e_team_id_513080_idx')],
            },
        ),
        migrations.CreateModel(
            name='GamePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(choices=[('elo_v1', 'Elo v1'), ('logistic_v1', 'Logistic Regression v1'), ('ensemble_v1', 'Ensemble v1')], default='ensemble_v1', max_length=20)),
                ('home_win_prob', models.FloatField()),
                ('away_win_prob', models.FloatField()),
                ('draw_prob', models.FloatField(default=0.0)),
                ('predicted_spread', models.FloatField(blank=True, null=True)),
                ('predicted_total', models.FloatField(blank=True, null=True)),
                ('elo_home_win_prob', models.FloatField(blank=True, null=True)),
                ('logistic_home_win_prob', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.5)),
                ('adjustments_applied', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='sports.game')),
            ],
            options={
                'ordering': ['-game__game_date'],
                'indexes': [models.Index(fields=['game', 'model_version'], name='analytics_g_game_id_28e011_idx')],
                'unique_together': {('game', 'model_version')},
            },
        ),
        migrations.CreateModel(
            name='PlayerPropProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_type', models.CharField(choices=[('NBA_PTS', 'NBA Points'), ('NBA_REB', 'NBA Rebounds'), ('NBA_AST', 'NBA Assists'), ('NBA_3PM', 'NBA 3-Pointers Made'), ('NBA_STL', 'NBA Steals'), ('NBA_BLK', 'NBA Blocks'), ('NBA_PRA', 'NBA Pts+Reb+Ast'), ('NFL_PASS_YDS', 'NFL Passing Yards'), ('NFL_PASS_TDS', 'NFL Passing TDs'), ('NFL_RUSH_YDS', 'NFL Rushing Yards'), ('NFL_REC_YDS', 'NFL Receiving Yards'), ('NFL_RECS', 'NFL Receptions'), ('NFL_RUSH_ATT', 'NFL Rush Attempts'), ('MLB_HITS', 'MLB Hits'), ('MLB_STRIKEOUTS', 'MLB Pitcher Strikeouts'), ('MLB_HR', 'MLB Home Runs'), ('MLB_RBI', 'MLB RBIs'), ('NHL_GOALS', 'NHL Goals'), ('NHL_ASSISTS', 'NHL Assists'), ('NHL_SHOTS', 'NHL Shots on Goal'), ('NHL_SAVES', 'NHL Goalie Saves'), ('SOC_SHOTS', 'Soccer Shots'), ('SOC_GOALS', 'Soccer Goals')], max_length=20)),
                ('projected_value', models.FloatField()),
                ('floor_value', models.FloatField(blank=True, null=True)),
                ('ceiling_value', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.5)),
                ('games_sampled', models.IntegerField(default=0)),
                ('model_version', models.CharField(default='rolling_v1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_projections', to='sports.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_projections', to='sports.player')),
            ],
            options={
                'ordering': ['-game__game_date'],
                'indexes': [models.Index(fields=['player', 'game'], name='analytics_p_player__7e25da_idx')],
                'unique_together': {('player', 'game', 'prop_type', 'model_version')},
            },
        ),
    ]
